### ISSUE TITLE
NFT Detail page

### ISSUE THREAD

**Issue by danmugh** [ongama-team/ongama-nft-web-app#20]
<img width="1440" alt="NFT Detail Page" src="https://user-images.githubusercontent.com/71265852/168757676-1c137b01-bcc4-4630-9dd1-d1155e1376a7.png">

<img width="528" alt="NFT Detail Page__" src="https://user-images.githubusercontent.com/71265852/168757709-34a53017-6975-4200-a3ef-77df370ee688.png">

<img width="251" alt="NFT Detail Page__ Option Click" src="https://user-images.githubusercontent.com/71265852/168758106-f5825011-0553-46f7-9e16-70e0ab815ea9.png">

**Comment by merdikim** [comment]
@danmugh can this task be reassigned to someone else ? I am not able to work on it for the moment due to time

**Comment by danmugh** [comment]
> @danmugh can this task be reassigned to someone else ? I am not able to work on it for the moment due to time

Alright
